### ISSUE TITLE
iCub MED-ical 27/1/2023

### ISSUE THREAD

**Issue by LZC-68** [event-driven-robotics/event-driven-demos#5]
arren, luna, simon, zhichao 

### Maintenance

 - [ ] camera FPGA/driver issues. Missing data at edges, not guaranteed to start first time and you need expert knowledge to reset it. https://github.com/robotology/event-driven/issues/166
 - [ ] zynqGrabber update for splitting channels/skin.
 -  normally done in vPreProcess but early tests show that the new ultrascale should be able to handle the load.
 - problem with skin labeling in the bit pattern so we can't tell if it's vision or skin?
- [ ] update firmware?
-  last updated by Luna and Marco, Summer 2022. So we probably need to look at it.
-  we should also find a link to instructions on how to do this.
- [ ] update software (YARP/event-driven etc.)
-  superbuild probably needs a pull
- update instructions on how to do this
- [ ] follow up on open hardware issues
-  we should open a ticket about the missing face.
- [ ] open issue for discussion on updating fingertips
-  we should open a ticket to discuss viability of updating fingertips
- [ ] merge ev2
- [ ] write TODO list for each icub-MED-ical

### Education

- [ ] how the event-driven pipeline works. cameras + skin hardware, ultrascale firmware etc., zynqGrabber, 
- [ ] boot up the robot correctly, and turn on event-cameras etc.
- [ ] yarp stuff, best practices for yarp network, datadumper, data player, yarpmanger
- [ ] how to control the robot with kinematics
- [ ] how to run the demos
- [ ] how to calibrate cameras

### Demos

- [ ] visualisation
-  stereo?
- skin?
- icub-breathers
- [ ] 2D vision tracking of paddle/ball with gaze following
-  update with ev2 and restructure the code to be 1 c++
- [ ] 6-DoF object tracking
- test if it works with on-board cameras
- robust initialisation
- [ ] HPE
- install it on the icub laptops
- [ ] braille
- new fingertips, code for the movement, demo framework. 
- [ ] visuo-tactile ultra-grasping
- here is an idea for the future to try to combine vision and tactile in a simple demo such that it might promote research in this direction

**Comment by arrenglover** [comment]
- [x] robotology-superbuild on icub-head was updated
- [ ] we tried to update the firmware but got stuck on robotology-superbuild not updating the files for icub-firmware-build, so the latest firmware was not available. @lunagava was going to ask if we did something wrong.

**Comment by lunagava** [comment]
I uploaded the last applications for the firmware and checked the yarprobotinterface works starting the robot correctly

![WhatsApp Image 2023-01-27 at 16 54 20](https://user-images.githubusercontent.com/45895918/215130009-a0762d8b-e51e-4723-a496-cc3119e45bbf.jpeg)

**Comment by arrenglover** [comment]
> I had to git pull inside icub-firmware-build

did you find out why this was required. i.e. why icub-firmware-build is not updated when robotology-superbuild is updated? The solution you did is a work-around, can we fix the problem?

**Comment by lunagava** [comment]
The icub-firmware guy told me that usually when you do git pull inside robotology-superbuild, the icub-firmware-build should be updated as well. He suggested me doing a git fetch --all and checking that everything is on master and not on a specific version but I already did a git pull inside icub-firmware-build so now it is difficult to simulate again the problem.

**Comment by lunagava** [comment]
The icub-firmware-build is not supposed to be inside robotology-superbuild. Someone has git clone wrongly inside.
